name: SavageClasses
version: 1.0
api-version: 1.8.8
main: apallo.savage.savageclasses.SavageClasses
depend: [WorldGuard, WorldEdit, Factions]
permissions:
  savageclasses.class.change:
    description: Allows free use of class changes.
    default: op
  savageclasses.class.change.others:
    description: Change another players class.
    default: op
commands:
  class:
    description: Savage Classes
    usage: "Usage: /<command>"